version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/bento-starter-docs

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies

      - run:
          name: 'Install dependencies'
          command: npm i

      - save_cache:
          paths:
            - ~/.cache
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: 'Run prettier check on project files'
          command: npm run prettier:check

      - run:
          name: 'Build'
          command: npm run build

      - run:
          name: 'Netlify deploy'
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              npm run netlify:deploy
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
